(0, 'outlook.office.com', 1, 'Exchange Online - Optimize Required')
(2, '(\.|^)outlook\.office\.com$', 1, 'Exchange Online - Allow Optimal - IMAP4')
(0, 'outlook.office365.com', 1, 'Exchange Online - Optimize Required')
(2, '(\.|^)outlook\.office\.com$', 1, 'Exchange Online - Allow Optimal - IMAP4')
(0, 'smtp.office365.com', 1, 'Exchange Online - Allow Required')
(0, 'r1.res.office365.com', 1, 'Exchange Online - Default Required')
(0, 'r3.res.office365.com', 1, 'Exchange Online - Default Required')
(0, 'r4.res.office365.com', 1, 'Exchange Online - Default Required')
(2, '(\.|^)outlook\.com$', 1, 'Exchange Online - Default Required')
(2, '(\.|^)outlook\.office\.com$', 1, 'Exchange Online - Default Required')
(0, 'attachments.office.net', 1, 'Exchange Online - Default Required')
(2, '(\.|^)protection\.outlook\.com$', 1, 'Exchange Online - Allow Required')
(2, '(\.|^)mail\.protection\.outlook\.com$', 1, 'Exchange Online - Allow Required')
(0, 'storage.live.com', 1, 'SPO and OneDrive - Supportability')
(0, 'admin.onedrive.com', 1, 'SPO and OneDrive - Default Required')
(0, 'officeclient.microsoft.com', 1, 'SPO and OneDrive - Default Required')
(2, '(\.|^)sharepointonline\.com$', 1, 'SPO and OneDrive - Default Required')
(0, 'cdn.sharepointonline.com', 1, 'SPO and OneDrive - Default Required')
(0, 'privatecdn.sharepointonline.com', 1, 'SPO and OneDrive - Default Required')
(0, 'publiccdn.sharepointonline.com', 1, 'SPO and OneDrive - Default Required')
(0, 'spoprod-a.akamaihd.net', 1, 'SPO and OneDrive - Default Required')
(0, 'static.sharepointonline.com', 1, 'SPO and OneDrive - Default Required')
(0, 'teams.microsoft.com', 1, 'Microsoft Teams - Allow Required')
(2, '(\.|^)lync\.com$', 1, 'Microsoft Teams - Allow Required')
(2, '(\.|^)teams\.microsoft\.com$', 1, 'Microsoft Teams - Allow Required')
(0, 'broadcast.skype.com', 1, 'Microsoft Teams - Allow Required')
(2, '(\.|^)broadcast\.skype\.com$', 1, 'Microsoft Teams - Allow Required')
(2, '(\.|^)sfbassets\.com$', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)urlp\.sfbassets\.com', 1, 'Microsoft Teams - Default Required')
(0, 'skypemaprdsitus.trafficmanager.net', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)keydelivery\.mediaservices\.windows\.net$', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)msecnd\.net$', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)streaming\.mediaservices\.windows\.net$', 1, 'Microsoft Teams - Default Required')
(0, 'ajax.aspnetcdn.com', 1, 'Microsoft Teams - Default Required')
(0, 'mlccdn.blob.core.windows.net', 1, 'Microsoft Teams - Default Required')
(0, 'aka.ms', 1, 'Microsoft Teams - Default Required')
(0, 'amp.azure.net', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)users\.storage\.live\.com$', 1, 'Microsoft Teams - Default Optional - Federation')
(2, '(\.|^)skypeforbusiness\.com$', 1, 'Microsoft Teams - Allow Optional - Skype Interop')
(2, '(\.|^)msedge\.net$', 1, 'Microsoft Teams - Default Required')
(0, 'compass-ssl.microsoft.com', 1, 'Microsoft Teams - Default Required')
(2, '(\.|^)tenor\.com$', 1, 'Microsoft Teams - Allow Optional - Yammer')
(2, '(\.|^)skype\.com$', 1, 'Microsoft Teams - Default Required')
(3, 'statics.teams.microsoft.com', 1, 'Microsoft Teams Telemetry')
(0, 'ajax.aspnetcdn.com', 1, 'Microsoft O365 Common - Video CDN')
(0, 'r3.res.outlook.com', 1, 'Microsoft O365 Common - Video CDN')
(0, 'spoprod-a.akamaihd.net', 1, 'Microsoft O365 Common - Video CDN')
(2, '(\.|^)api\.microsoftstream\.com$', 1, 'Microsoft O365 Common - Stream')
(2, '(\.|^)notification\.api\.microsoftstream\.com$', 1, 'Microsoft O365 Common - Stream')
(0, 'api.microsoftstream.com', 1, 'Microsoft O365 Common - Stream')
(0, 'web.microsoftstream.com', 1, 'Microsoft O365 Common - Stream')
(2, '(\.|^)azureedge\.net$', 1, 'Microsoft O365 Common - Stream')
(2, '(\.|^)media\.azure\.net$', 1, 'Microsoft O365 Common - Stream')
(2, '(\.|^)officeapps\.live\.com$', 1, 'Microsoft O365 Common - Stream')
(2, '(\.|^)online\.office\.com$', 1, 'Microsoft O365 Common - Allow Required')
(0, 'office.live.com', 1, 'Microsoft O365 Common - Allow Required')
(2, '(\.|^)onenote\.com$', 1, 'Microsoft O365 Common - Default Required - OneNote')
(2, '(\.|^)office\.net$', 1, 'Microsoft O365 Common - Default Required - OneNote')
(2, '(\.|^)cdn\.onenote\.net$', 1, 'Microsoft O365 Common - Default Required - OneNote')
(2, '(\.|^)msftidentity\.com$', 1, 'Microsoft O365 Common - Allow Required')
(2, '(\.|^)msidentity\.com$', 1, 'Microsoft O365 Common - Allow Required')
(0, 'account.activedirectory.windowsazure.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'accounts.accesscontrol.windows.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'adminwebservice.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'api.passwordreset.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'autologon.microsoftazuread-sso.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'becws.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'clientconfig.microsoftonline-p.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'companymanager.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'device.login.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'graph.microsoft.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'graph.windows.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'login.microsoft.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'login.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'login.microsoftonline-p.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'login.windows.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'logincert.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'loginex.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'login-us.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'nexus.microsoftonline-p.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'passwordreset.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'provisioningapi.microsoftonline.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'logincdn.msauth.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'main.iam.ad.ext.azure.com', 1, 'Azure AD Login Page that often gets blocked by regex.')
(2, '(\.|^)manage\.office\.com$', 1, 'Microsoft O365 Common - Allow Required')
(2, '(\.|^)protection\.office\.com$', 1, 'Microsoft O365 Common - Allow Required')
(0, 'manage.office.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'protection.office.com', 1, 'Microsoft O365 Common - Allow Required')
(2, '(\.|^)portal\.cloudappsecurity\.com$', 1, 'Microsoft O365 Common - Allow Required')
(0, 'account.office.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'admin.microsoft.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'home.office.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'portal.office.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'www.office.com', 1, 'Microsoft O365 Common - Allow Required')
(0, 'suite.office.net', 1, 'Microsoft O365 Common - Allow Required')
(0, 'mlccdn.blob.core.windows.net', 1, 'Microsoft O365 Common - Allow Required')
(3, '(\.|^)log\.optimizely\.com$', 1, 'Microsoft O365 Telemetry')
(1, 'vortex.data.microsoft.com', 1, 'Microsoft O365 Telemetry')
(1, 'acompli.helpshift.com', 1, 'Microsoft O365 Telemetry')
(1, 'analytics.localytics.com', 1, 'Microsoft O365 Telemetry')
(1, 'api.localytics.com', 1, 'Microsoft O365 Telemetry')
(1, 'sdk.hockeyapp.net', 1, 'Microsoft O365 Telemetry')
(1, 'web.localytics.com', 1, 'Microsoft O365 Telemetry')
(1, 'webanalytics.localytics.com', 1, 'Microsoft O365 Telemetry')
(1, 'telemetryservice.firstpartyapps.oaspapps.com', 1, 'Microsoft O365 Telemetry')
(1, 'watson.telemetry.microsoft.com', 1, 'Microsoft O365 Telemetry')
(1, 'data.flurry.com', 1, 'Microsoft O365 Telemetry')
(1, 'app.adjust.com', 1, 'Microsoft O365 Telemetry')
(1, 'activity.windows.com', 1, 'Microsoft O365 Telemetry')